hydra:
  run:
    dir: ${output_dir}/${data.task_name}/${ue.dropout_type}_${ue.dropout_subs}/${data.subsample_perc}/${suffix}/${now:%Y-%m-%d}/${now:%H-%M-%S}-${repeat}
model:
    model_name_or_path: 'google/electra-base-discriminator'
    tokenizer_name: ''
    n_epochs: 4
    already_finetuned: false
ue:
    dropout_type: 'MC'
    inference_prob: 0.1
    committee_size: 20
    dropout_subs: 'last'
    eval_bs: 1000
    use_cache: True
    eval_passes: False
    dropout:
        max_n: 100
        max_frac: 0.4
        mask_name: 'dpp'
        dry_run_dataset: 'eval'

training:
    seed: 101
    learning_rate: 5e-5
    per_device_eval_batch_size: 800
    per_device_train_batch_size: 16
    num_train_epochs: 4

data:
    task_name: 'mrpc'
    data_dir: '../workdir/glue_data/MRPC/'
    subsample_perc: 0.
cache_dir: '../workdir/cache/'
output_dir: '../workdir/results/'
repeat: 0
do_predict: True
seed: 42
suffix: ''
do_train: True
do_eval: True
